CREATE TYPE ACCESS_TYPE AS enum ('ROLE_BASED', 'EXPLICIT');
CREATE TYPE ROLE_TYPE AS enum ('IDAM', 'RESOURCE');

ALTER TABLE roles
  ADD COLUMN access_management_type ACCESS_TYPE NOT NULL;

ALTER TABLE roles
  ALTER COLUMN role_type TYPE ROLE_TYPE USING role_type::ROLE_TYPE;

ALTER TYPE SECURITYCLASSIFICATION RENAME TO SECURITY_CLASSIFICATION;
